### ISSUE TITLE
TypeError: Object function (req, res, next) {app.handle(req, res, next);} has no method 'configure'

### ISSUE THREAD

**Issue by oriramikad** [dannytatom/muddy#12]
```
C:\muddy\init.js:23
app.configure(function() {
    ^
TypeError: Object function (req, res, next) {
    app.handle(req, res, next);
  } has no method 'configure'
    at Object.<anonymous> (C:\hsd\muddy\init.js:23:5)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

**Comment by dannytatom** [comment]
Fixed now, only 2 years late!
